# Generated by Django 4.2.11 on 2026-01-28 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0029_alter_electro_title_alter_gas_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Введите только буквы.', regex='^[A-Za-zА-Яа-яЁё]+(?: [A-Za-zА-Яа-яЁё]+)*$')], verbose_name='Имя'),
        ),
    ]
