# Generated by Django 5.2.6 on 2026-01-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0029_alter_electro_title_alter_gas_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
